### ISSUE TITLE
build error when running on windows

### ISSUE THREAD

**Issue by philippe-richard** [zowe/cpu_usage_sample#4]
if i run this maven job on windows, the compile works fine, but the maven clean verify fails because the 'pax' utility is not available on that platform.
INFO] ------------------------------------------------------------------------
INFO] BUILD FAILURE
INFO] ------------------------------------------------------------------------
INFO] Total time:  02:12 min
INFO] Finished at: 2019-03-14T14:49:28+01:00
INFO] ------------------------------------------------------------------------
ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.5.0:exec (package-atlas) on project cpu: Command ex
cution failed.: Cannot run program "pax" (in directory "C:\Program Files\Docker Toolbox\cpu_usage_sample"): CreateProce
s error=2, The system cannot find the file specified -> [Help 1]
ERROR]
ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
ERROR] Re-run Maven using the -X switch to enable full debug logging.
ERROR]
ERROR] For more information about the errors and possible solutions, please read the following articles:
ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

However i did ftp the install.sh , run-cpu-usage.sh  and cpu-1.0.0.jar     to my z/OS host and run the install script there.
i recycled my zowesvr server and run the run-cpu-usage.sh script afterwards.
The URL https://xxx.xxx.xxx.xxx:3199/swagger-ui.html returned the expected output:
{
  "system": {
    "systemName": "X9",
    "CPUUsage": "2",
    "ZAAPUsage": "0",
    "ZIIPUsage": "0",
    "pagingRate": "5",
    "totalEXCPRate": "0.0"
  },
  "addressSpaces": [
    {
      "jobId": "STC00875",
      "CPU": "0.27",
      "EXCPRate": "0.00"
    },
    {
      "jobId": "TSU01057",
      "CPU": "0.00",
      "EXCPRate": "0.00"
    }
  ]
}
So my question is: is it possible to validate the platform, and if on windows, then skip the pax step to avoid the build error. Maybe just send a warning that all 3 files must be ftp'ed to the zowe server host and use as such.
thank you, Philippe R.

**Comment by Colin-Stone** [comment]
Hi Philippe. Thanks for highlighting this and good to see you have it up and running under z. I had not seen this issue simply because I have been using OSx or Linux which does support Pax albeit not as comprehensively as on z. I think this issue will come up every time we use pax as part of our sample build process in our samples. 
So I will capture your recommendation in the Readme for now

**Comment by philippe-richard** [comment]
Hi Colin,
txs for the quick answer, and for the good job you have done with that 
sample zowe REST API application, very instructive even for dummies like 
me, who are just mainframe folks.
i understabnd almost nothing about  maven spring boot and the likes, but i 
was able to get it up and running on my z/OS host.

Just an additional comment: 
would be useful to indicate that the port number you define in 

install.sh 



run-cpu-usage.sh



should be any port of your choosing , which is currently not in use in 
your TCPIP config. (ex: 3199 for me)

i had a hard time trying to figure out what port number to configure.  I 
initially thought it had to be the zlux server or the explorer server, but 
then i got error messages indicating that the port was in use.

# - Port number to run this from


PORT={available_port_number} 

Anyway it was a very nice exercise for me...

Cordialement, Philippe
  ====================

Philippe richard1/France/IBM@IBMFR (n'oubliez pas le 1...)
IBM Client Center, Montpellier

mailto:philippe_richard@fr.ibm.com   Mail: Cie IBM France Sce 146301
Phone: +33 4 6799580705 (38 0705)    Rue de la Vieille Poste -CS 81021
Fax:       +33 4 67346477                      34060 Montpellier Cedex  2

**Comment by Colin-Stone** [comment]
Thanks again. I've included that in too

**Comment by philippe-richard** [comment]
cool !


Cordialement, Philippe
  ====================

Philippe richard1/France/IBM@IBMFR (n'oubliez pas le 1...)
IBM Client Center, Montpellier

mailto:philippe_richard@fr.ibm.com   Mail: Cie IBM France Sce 146301
Phone: +33 4 6799580705 (38 0705)    Rue de la Vieille Poste -CS 81021
Fax:       +33 4 67346477                      34060 Montpellier Cedex  2

**Comment by Colin-Stone** [comment]
Incorporated comments into readme, closing issue
